### ISSUE TITLE
Failed to resolve implementation

### ISSUE THREAD

**Issue by Chinmay891** [tejmagar/AndroidWiFiTools#5]
Failed to resolve: com.github.tejmagar:AndroidWiFiTools:1.0.2
This warning showed up when I tried to implement the library.
Please Help!

**Comment by tejmagar** [comment]
Hi, if you are using latest gradle, you need to update the settings.gradle file with
` maven { url 'https://jitpack.io' }
    `

**Comment by Chinmay891** [comment]
Yes I am on  Gradle 8.0 and I updated the settings.gradle too still its not working. Also I have testing device which is on Android 11 and previous issue shows it does not give MAC address on Android 11 so what is the solution for Android 11 devices,

**Comment by tejmagar** [comment]
Hi, android 11 doesn't allow to run arp commands and restricts access to mac address. Hence you need to target older api level.
Update your build.gradle(:app)
```
android {
    ...
    defaultConfig {
        ...
        //noinspection OldTargetApi
        targetSdkVersion 29
        ...
        }
}

**Comment by Chinmay891** [comment]
Hey there, 
Is there any way to get MAC Address in Android 11. If there is, please let me know.
Thanks in advance!

**Comment by tejmagar** [comment]
Hi, if you set target sdk version to 29 or below, you can still access mac address in Android 11. But according to new google developer policy, you may not be allowed to target below sdk level 30.

**Comment by Chinmay891** [comment]
I have set the target sdk to 29 still it does not show MAC Address on Android 11. Still thank you for your response!!
If there is any other way please let me know.
Thanks!
