### ISSUE TITLE
Notify listener from background worker

### ISSUE THREAD

**Issue by ashraf-atef** [tejmagar/AndroidWiFiTools#7]
We got cast exception due to casting the context to activity if we passed a context of background worker or something like that.
 ((Activity)context).runOnUiThread(() -> deviceFindListener.onDeviceFound(deviceItem));
 
 Can you provide another solution for notifying the listener without depending on activity?

**Comment by tejmagar** [comment]
Check this optimized version if it works for you: https://github.com/tejmagar/AndroidNetworkTools
