### ISSUE TITLE
MacAdress Not found in Android 11 31 Api

### ISSUE THREAD

**Issue by rizwankhanMiranshah** [tejmagar/AndroidWiFiTools#8]
Kindly Fix this Issue

**Comment by tejmagar** [comment]
Hi, it is not possible to access MacAddress in Android 11 with target SDK 31.
You need to use target SDK 29 or below.
More information: [https://developer.android.com/about/versions/11/privacy/mac-address](https://developer.android.com/about/versions/11/privacy/mac-address)
